'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class wfCurrency_Ajax

	'''<summary>
	'''MainStyle control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents MainStyle As Global.System.Web.UI.HtmlControls.HtmlLink

	'''<summary>
	'''wfgroup control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents wfgroup As Global.System.Web.UI.HtmlControls.HtmlForm

	'''<summary>
	'''ScriptManager1 control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents ScriptManager1 As Global.System.Web.UI.ScriptManager

	'''<summary>
	'''upnlMSGBox control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents upnlMSGBox As Global.System.Web.UI.UpdatePanel

	'''<summary>
	'''MSGBoxCtrl control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents MSGBoxCtrl As Global.Flypal.MSGBox

	'''<summary>
	'''upnlTitle control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents upnlTitle As Global.System.Web.UI.UpdatePanel

	'''<summary>
	'''lblTitle control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents lblTitle As Global.System.Web.UI.WebControls.Label

	'''<summary>
	'''btnAdd control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents btnAdd As Global.System.Web.UI.WebControls.Button

	'''<summary>
	'''btnSave control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents btnSave As Global.System.Web.UI.WebControls.Button

	'''<summary>
	'''btnClose control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents btnClose As Global.System.Web.UI.WebControls.Button

	'''<summary>
	'''favICN control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents favICN As Global.System.Web.UI.HtmlControls.HtmlGenericControl

	'''<summary>
	'''upnlValidationSummary control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents upnlValidationSummary As Global.System.Web.UI.UpdatePanel

	'''<summary>
	'''Validationsummary1 control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents Validationsummary1 As Global.System.Web.UI.WebControls.ValidationSummary

	'''<summary>
	'''rfvName control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents rfvName As Global.System.Web.UI.WebControls.RequiredFieldValidator

	'''<summary>
	'''cvName control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents cvName As Global.System.Web.UI.WebControls.CustomValidator

	'''<summary>
	'''rfvConvFactor control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents rfvConvFactor As Global.System.Web.UI.WebControls.RequiredFieldValidator

	'''<summary>
	'''cvConvFactor control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents cvConvFactor As Global.System.Web.UI.WebControls.CustomValidator

	'''<summary>
	'''rfvSymbol control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents rfvSymbol As Global.System.Web.UI.WebControls.RequiredFieldValidator

	'''<summary>
	'''upnlCurrencyDetails control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents upnlCurrencyDetails As Global.System.Web.UI.UpdatePanel

	'''<summary>
	'''txtCurrencyName control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents txtCurrencyName As Global.System.Web.UI.WebControls.TextBox

	'''<summary>
	'''txtNameAfterDecimal control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents txtNameAfterDecimal As Global.System.Web.UI.WebControls.TextBox

	'''<summary>
	'''txtSymbol control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents txtSymbol As Global.System.Web.UI.WebControls.TextBox

	'''<summary>
	'''txtConvFactor control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents txtConvFactor As Global.System.Web.UI.WebControls.TextBox

	'''<summary>
	'''upnlGridView control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents upnlGridView As Global.System.Web.UI.UpdatePanel

	'''<summary>
	'''lblResult control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents lblResult As Global.System.Web.UI.WebControls.Label

	'''<summary>
	'''dgCurrency control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents dgCurrency As Global.System.Web.UI.WebControls.GridView

	'''<summary>
	'''upnlFavIcnBtn control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents upnlFavIcnBtn As Global.System.Web.UI.UpdatePanel

	'''<summary>
	'''hdnBtnMarkFavourite control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents hdnBtnMarkFavourite As Global.System.Web.UI.WebControls.Button

	'''<summary>
	'''hdnBtnRemoveFavourite control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents hdnBtnRemoveFavourite As Global.System.Web.UI.WebControls.Button

	'''<summary>
	'''AjaxLoader control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents AjaxLoader As Global.System.Web.UI.UpdateProgress
End Class
