'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class DiscrepancyCorrectiveActionListPage

	'''<summary>
	'''Head control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents Head As Global.System.Web.UI.HtmlControls.HtmlHead

	'''<summary>
	'''MainStyle control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents MainStyle As Global.System.Web.UI.HtmlControls.HtmlLink

	'''<summary>
	'''frmDiscrepancyList control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents frmDiscrepancyList As Global.System.Web.UI.HtmlControls.HtmlForm

	'''<summary>
	'''ScriptManager1 control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents ScriptManager1 As Global.System.Web.UI.ScriptManager

	'''<summary>
	'''upnlMSGBox control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents upnlMSGBox As Global.System.Web.UI.UpdatePanel

	'''<summary>
	'''MSGBoxCtrl control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents MSGBoxCtrl As Global.Flypal.MSGBox

	'''<summary>
	'''pnlMain control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents pnlMain As Global.System.Web.UI.WebControls.Panel

	'''<summary>
	'''upnlTitle control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents upnlTitle As Global.System.Web.UI.UpdatePanel

	'''<summary>
	'''lblTitle control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents lblTitle As Global.System.Web.UI.WebControls.Label

	'''<summary>
	'''upnlActionBtnTop control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents upnlActionBtnTop As Global.System.Web.UI.UpdatePanel

	'''<summary>
	'''btnAddNew control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents btnAddNew As Global.System.Web.UI.WebControls.Button

	'''<summary>
	'''btnClose control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents btnClose As Global.System.Web.UI.WebControls.Button

	'''<summary>
	'''favICN control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents favICN As Global.System.Web.UI.HtmlControls.HtmlGenericControl

	'''<summary>
	'''Validationsummary2 control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents Validationsummary2 As Global.System.Web.UI.WebControls.ValidationSummary

	'''<summary>
	'''rfvFromDate control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents rfvFromDate As Global.System.Web.UI.WebControls.RequiredFieldValidator

	'''<summary>
	'''rfvToDate control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents rfvToDate As Global.System.Web.UI.WebControls.RequiredFieldValidator

	'''<summary>
	'''upnlSearchCriteria control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents upnlSearchCriteria As Global.System.Web.UI.UpdatePanel

	'''<summary>
	'''lblAircraft control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents lblAircraft As Global.System.Web.UI.WebControls.Label

	'''<summary>
	'''cmbAircraft control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents cmbAircraft As Global.System.Web.UI.WebControls.DropDownList

	'''<summary>
	'''lblDiscrepancyNo control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents lblDiscrepancyNo As Global.System.Web.UI.WebControls.Label

	'''<summary>
	'''upnlDiscrepancyNo control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents upnlDiscrepancyNo As Global.System.Web.UI.UpdatePanel

	'''<summary>
	'''txtText control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents txtText As Global.System.Web.UI.WebControls.TextBox

	'''<summary>
	'''txtText1_Autocomplete control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents txtText1_Autocomplete As Global.AjaxControlToolkit.AutoCompleteExtender

	'''<summary>
	'''txtNo control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents txtNo As Global.System.Web.UI.WebControls.TextBox

	'''<summary>
	'''lblFromDate control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents lblFromDate As Global.System.Web.UI.WebControls.Label

	'''<summary>
	'''txtFromDate control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents txtFromDate As Global.System.Web.UI.WebControls.TextBox

	'''<summary>
	'''txtFromDate_CalendarExtender control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents txtFromDate_CalendarExtender As Global.AjaxControlToolkit.CalendarExtender

	'''<summary>
	'''FromDate_watermarkextender control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents FromDate_watermarkextender As Global.AjaxControlToolkit.TextBoxWatermarkExtender

	'''<summary>
	'''cvFromDate control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents cvFromDate As Global.System.Web.UI.WebControls.CustomValidator

	'''<summary>
	'''lblToDate control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents lblToDate As Global.System.Web.UI.WebControls.Label

	'''<summary>
	'''txtToDate control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents txtToDate As Global.System.Web.UI.WebControls.TextBox

	'''<summary>
	'''txtToDate_CalendarExtender1 control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents txtToDate_CalendarExtender1 As Global.AjaxControlToolkit.CalendarExtender

	'''<summary>
	'''ToDate_watermarkextender control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents ToDate_watermarkextender As Global.AjaxControlToolkit.TextBoxWatermarkExtender

	'''<summary>
	'''lblInfo control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents lblInfo As Global.System.Web.UI.WebControls.Label

	'''<summary>
	'''btnFindNow control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents btnFindNow As Global.System.Web.UI.WebControls.ImageButton

	'''<summary>
	'''upnlCollapsiblePnl control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents upnlCollapsiblePnl As Global.System.Web.UI.UpdatePanel

	'''<summary>
	'''pnlAdvancedSearch control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents pnlAdvancedSearch As Global.System.Web.UI.WebControls.Panel

	'''<summary>
	'''lblMastersSelection control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents lblMastersSelection As Global.System.Web.UI.WebControls.Label

	'''<summary>
	'''upnlAvanceSearchContent control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents upnlAvanceSearchContent As Global.System.Web.UI.UpdatePanel

	'''<summary>
	'''pnlAdvancedSearchContent control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents pnlAdvancedSearchContent As Global.System.Web.UI.WebControls.Panel

	'''<summary>
	'''lblAssembly control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents lblAssembly As Global.System.Web.UI.WebControls.Label

	'''<summary>
	'''cmbAssembly control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents cmbAssembly As Global.System.Web.UI.WebControls.DropDownList

	'''<summary>
	'''lblATAChapter control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents lblATAChapter As Global.System.Web.UI.WebControls.Label

	'''<summary>
	'''cmbATAChapter control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents cmbATAChapter As Global.System.Web.UI.WebControls.DropDownList

	'''<summary>
	'''lblIncidentType control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents lblIncidentType As Global.System.Web.UI.WebControls.Label

	'''<summary>
	'''cmbIncidentType control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents cmbIncidentType As Global.System.Web.UI.WebControls.DropDownList

	'''<summary>
	'''lblStatus control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents lblStatus As Global.System.Web.UI.WebControls.Label

	'''<summary>
	'''cmbStatus control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents cmbStatus As Global.System.Web.UI.WebControls.DropDownList

	'''<summary>
	'''lblMELOrDeviation control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents lblMELOrDeviation As Global.System.Web.UI.WebControls.Label

	'''<summary>
	'''cmbMELSnag control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents cmbMELSnag As Global.System.Web.UI.WebControls.DropDownList

	'''<summary>
	'''lblDefectType control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents lblDefectType As Global.System.Web.UI.WebControls.Label

	'''<summary>
	'''cmbDefectType control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents cmbDefectType As Global.System.Web.UI.WebControls.DropDownList

	'''<summary>
	'''clpextAdvancedSearch control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents clpextAdvancedSearch As Global.AjaxControlToolkit.CollapsiblePanelExtender

	'''<summary>
	'''upnlResult control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents upnlResult As Global.System.Web.UI.UpdatePanel

	'''<summary>
	'''lblResult control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents lblResult As Global.System.Web.UI.WebControls.Label

	'''<summary>
	'''spnImportFromCRS control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents spnImportFromCRS As Global.System.Web.UI.HtmlControls.HtmlGenericControl

	'''<summary>
	'''iImportFromCRS control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents iImportFromCRS As Global.System.Web.UI.HtmlControls.HtmlGenericControl

	'''<summary>
	'''upnlShowEntriesDDL control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents upnlShowEntriesDDL As Global.System.Web.UI.UpdatePanel

	'''<summary>
	'''lblShowEntriesDDL control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents lblShowEntriesDDL As Global.System.Web.UI.WebControls.Label

	'''<summary>
	'''ddlShowEntries control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents ddlShowEntries As Global.System.Web.UI.WebControls.DropDownList

	'''<summary>
	'''upnlGridView control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents upnlGridView As Global.System.Web.UI.UpdatePanel

	'''<summary>
	'''dgDiscrepancyCorrectiveActionList control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents dgDiscrepancyCorrectiveActionList As Global.System.Web.UI.WebControls.GridView

	'''<summary>
	'''upnlFavIcnBtn control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents upnlFavIcnBtn As Global.System.Web.UI.UpdatePanel

	'''<summary>
	'''hdnBtnMarkFavourite control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents hdnBtnMarkFavourite As Global.System.Web.UI.WebControls.Button

	'''<summary>
	'''hdnBtnRemoveFavourite control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents hdnBtnRemoveFavourite As Global.System.Web.UI.WebControls.Button

	'''<summary>
	'''hdnBtnImportCRSLogs control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents hdnBtnImportCRSLogs As Global.System.Web.UI.WebControls.Button

	'''<summary>
	'''upnlHiddenButtons control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents upnlHiddenButtons As Global.System.Web.UI.UpdatePanel

	'''<summary>
	'''hdnBtnDiscrepancyTroubleShoot control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents hdnBtnDiscrepancyTroubleShoot As Global.System.Web.UI.WebControls.Button

	'''<summary>
	'''hdnBtnModelInspMaster control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents hdnBtnModelInspMaster As Global.System.Web.UI.WebControls.Button

	'''<summary>
	'''AjaxLoader control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents AjaxLoader As Global.System.Web.UI.UpdateProgress

	'''<summary>
	'''btnDummyDiscrepancyDetail control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents btnDummyDiscrepancyDetail As Global.System.Web.UI.WebControls.Button

	'''<summary>
	'''pnlDiscrepancyDetail control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents pnlDiscrepancyDetail As Global.System.Web.UI.WebControls.Panel

	'''<summary>
	'''mdlPopupDiscrepancyDetail control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents mdlPopupDiscrepancyDetail As Global.AjaxControlToolkit.ModalPopupExtender

	'''<summary>
	'''btnDummyDiscrepancyTroubleShoot control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents btnDummyDiscrepancyTroubleShoot As Global.System.Web.UI.WebControls.Button

	'''<summary>
	'''pnlDiscrepancyTroubleShoot control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents pnlDiscrepancyTroubleShoot As Global.System.Web.UI.WebControls.Panel

	'''<summary>
	'''mdlPopupDiscrepancyTroubleShoot control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents mdlPopupDiscrepancyTroubleShoot As Global.AjaxControlToolkit.ModalPopupExtender

	'''<summary>
	'''btnDummyDiscrepancyTroubleshootView control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents btnDummyDiscrepancyTroubleshootView As Global.System.Web.UI.WebControls.Button

	'''<summary>
	'''pnlDiscrepancyTroubleshootView control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents pnlDiscrepancyTroubleshootView As Global.System.Web.UI.WebControls.Panel

	'''<summary>
	'''mdlPopupDiscrepancyTroubleshootView control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents mdlPopupDiscrepancyTroubleshootView As Global.AjaxControlToolkit.ModalPopupExtender

	'''<summary>
	'''btnDummyModelInspMaster control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents btnDummyModelInspMaster As Global.System.Web.UI.WebControls.Button

	'''<summary>
	'''pnlModelInspMaster control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents pnlModelInspMaster As Global.System.Web.UI.WebControls.Panel

	'''<summary>
	'''mdlPopupModelInspMaster control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents mdlPopupModelInspMaster As Global.AjaxControlToolkit.ModalPopupExtender
End Class
