'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class wfSalesInvoiceItem_Ajax

	'''<summary>
	'''Head1 control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents Head1 As Global.System.Web.UI.HtmlControls.HtmlHead

	'''<summary>
	'''MainStyle control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents MainStyle As Global.System.Web.UI.HtmlControls.HtmlLink

	'''<summary>
	'''form1 control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents form1 As Global.System.Web.UI.HtmlControls.HtmlForm

	'''<summary>
	'''ScriptManager1 control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents ScriptManager1 As Global.System.Web.UI.ScriptManager

	'''<summary>
	'''upnlMSGBox control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents upnlMSGBox As Global.System.Web.UI.UpdatePanel

	'''<summary>
	'''MSGBoxCtrl control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents MSGBoxCtrl As Global.Flypal.MSGBox

	'''<summary>
	'''upnlValidationSummary control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents upnlValidationSummary As Global.System.Web.UI.UpdatePanel

	'''<summary>
	'''lblTitle control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents lblTitle As Global.System.Web.UI.WebControls.Label

	'''<summary>
	'''upnlButtons control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents upnlButtons As Global.System.Web.UI.UpdatePanel

	'''<summary>
	'''btnSave control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents btnSave As Global.System.Web.UI.WebControls.Button

	'''<summary>
	'''btnBack control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents btnBack As Global.System.Web.UI.WebControls.Button

	'''<summary>
	'''Validationsummary2 control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents Validationsummary2 As Global.System.Web.UI.WebControls.ValidationSummary

	'''<summary>
	'''rfvPartNo control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents rfvPartNo As Global.System.Web.UI.WebControls.RequiredFieldValidator

	'''<summary>
	'''rfvQuantity control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents rfvQuantity As Global.System.Web.UI.WebControls.RequiredFieldValidator

	'''<summary>
	'''rfvPartDesc control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents rfvPartDesc As Global.System.Web.UI.WebControls.RequiredFieldValidator

	'''<summary>
	'''rfvRate control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents rfvRate As Global.System.Web.UI.WebControls.RequiredFieldValidator

	'''<summary>
	'''cvOtherCharge control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents cvOtherCharge As Global.System.Web.UI.WebControls.CustomValidator

	'''<summary>
	'''cvQty control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents cvQty As Global.System.Web.UI.WebControls.CustomValidator

	'''<summary>
	'''cvCRate control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents cvCRate As Global.System.Web.UI.WebControls.CustomValidator

	'''<summary>
	'''Panel3 control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents Panel3 As Global.System.Web.UI.WebControls.Panel

	'''<summary>
	'''upnlQuotationItem control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents upnlQuotationItem As Global.System.Web.UI.UpdatePanel

	'''<summary>
	'''txtSrNo control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents txtSrNo As Global.System.Web.UI.WebControls.TextBox

	'''<summary>
	'''txtPartNo control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents txtPartNo As Global.System.Web.UI.WebControls.TextBox

	'''<summary>
	'''imgbtnPartNo control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents imgbtnPartNo As Global.System.Web.UI.WebControls.ImageButton

	'''<summary>
	'''txtDescription control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents txtDescription As Global.System.Web.UI.WebControls.TextBox

	'''<summary>
	'''upnlSalesInvoiceItemInformation control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents upnlSalesInvoiceItemInformation As Global.System.Web.UI.UpdatePanel

	'''<summary>
	'''lblOrderIssueNo control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents lblOrderIssueNo As Global.System.Web.UI.WebControls.Label

	'''<summary>
	'''txtOrderIssueNo control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents txtOrderIssueNo As Global.System.Web.UI.WebControls.TextBox

	'''<summary>
	'''lblOrderIssueDate control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents lblOrderIssueDate As Global.System.Web.UI.WebControls.Label

	'''<summary>
	'''txtOrderIssueDate control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents txtOrderIssueDate As Global.System.Web.UI.WebControls.TextBox

	'''<summary>
	'''lblReceiptNo control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents lblReceiptNo As Global.System.Web.UI.WebControls.Label

	'''<summary>
	'''txtReceiptNo control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents txtReceiptNo As Global.System.Web.UI.WebControls.TextBox

	'''<summary>
	'''lblReceiptDate control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents lblReceiptDate As Global.System.Web.UI.WebControls.Label

	'''<summary>
	'''txtReceiptDate control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents txtReceiptDate As Global.System.Web.UI.WebControls.TextBox

	'''<summary>
	'''lblReleaseNote control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents lblReleaseNote As Global.System.Web.UI.WebControls.Label

	'''<summary>
	'''txtRelNoteNo control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents txtRelNoteNo As Global.System.Web.UI.WebControls.TextBox

	'''<summary>
	'''lblRelNoteDate control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents lblRelNoteDate As Global.System.Web.UI.WebControls.Label

	'''<summary>
	'''txtRelNoteDate control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents txtRelNoteDate As Global.System.Web.UI.WebControls.TextBox

	'''<summary>
	'''txtQty control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents txtQty As Global.System.Web.UI.WebControls.TextBox

	'''<summary>
	'''txtQtyUnit control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents txtQtyUnit As Global.System.Web.UI.WebControls.TextBox

	'''<summary>
	'''txtRate control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents txtRate As Global.System.Web.UI.WebControls.TextBox

	'''<summary>
	'''txtRateCurrency control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents txtRateCurrency As Global.System.Web.UI.WebControls.TextBox

	'''<summary>
	'''txtOtherCharges control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents txtOtherCharges As Global.System.Web.UI.WebControls.TextBox

	'''<summary>
	'''txtAmount control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents txtAmount As Global.System.Web.UI.WebControls.TextBox

	'''<summary>
	'''txtCEffRate control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents txtCEffRate As Global.System.Web.UI.WebControls.TextBox

	'''<summary>
	'''pnlRemarkNote control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents pnlRemarkNote As Global.System.Web.UI.WebControls.Panel

	'''<summary>
	'''cvRemark control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents cvRemark As Global.System.Web.UI.WebControls.CustomValidator

	'''<summary>
	'''txtRemark control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents txtRemark As Global.System.Web.UI.WebControls.TextBox

	'''<summary>
	'''cvNote control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents cvNote As Global.System.Web.UI.WebControls.CustomValidator

	'''<summary>
	'''txtNote control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents txtNote As Global.System.Web.UI.WebControls.TextBox

	'''<summary>
	'''AjaxLoader control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents AjaxLoader As Global.System.Web.UI.UpdateProgress
End Class
