Imports System.Text
Public Class wfServiceabilityMailSend_Ajax
    Inherits System.Web.UI.Page

#Region " Variable Declaration "
    Public mServiceabilityMailSend As ServiceabilityMailSend
    Public mRequisitionNew As RequisitionNew
    Dim mTransTypeID As Integer
    Dim mRequisitionCustomer As RequisitionCustomer
    Dim CustName As String = String.Empty
    Dim CustAddress As String = String.Empty
    Dim AircraftType As String = String.Empty
    Dim TextContents As New StringBuilder
#End Region

#Region " Business Methods "
    Private Sub getSession()
        mServiceabilityMailSend = Session("mServiceabilityMailSend")
    End Sub
    Private Sub setSession()
        Session("mRequisitionNew") = mRequisitionNew
    End Sub
    Private Sub FindNow(ByVal AsOnDate As Date)
        mServiceabilityMailSend = ServiceabilityMailSend.GetList(txtAsOnDate.Text, User.Identity.Name)
        Session("mServiceabilityMailSend") = mServiceabilityMailSend
        If mServiceabilityMailSend.Count > 0 Then
            TextContents.Append("The following aircraft are available for flying on " + "<b>" + txtAsOnDate.Text + ":</b>")
            TextContents.Append(vbCrLf)
            For i As Integer = 0 To mServiceabilityMailSend.Count - 1
                TextContents.Append(vbCrLf)
                TextContents.Append("•" + mServiceabilityMailSend(i).RegNo + " (" + mServiceabilityMailSend(i).Model + ")" + IIf(mServiceabilityMailSend(i).PriorityID <> 10, ": " + mServiceabilityMailSend(i).PriorityName, "") + IIf(mServiceabilityMailSend(i).Remark <> "", " (<b>" + mServiceabilityMailSend(i).Remark + "</b>)", ""))
                'TextContents.Append(mServiceabilityMailSend(i).RegNo + IIf(mServiceabilityMailSend(i).PriorityName <> "", ": " + mServiceabilityMailSend(i).PriorityName, "") + IIf(mServiceabilityMailSend(i).Remark <> "", mServiceabilityMailSend(i).Remark, ""))
            Next
            TextContents.Append(vbCrLf)
            TextContents.Append(vbCrLf)
            TextContents.Append("Aircraft serviceability for the day:" + mServiceabilityMailSend(0).AverageForDay.ToString + " %")
            TextContents.Append(vbCrLf)
            TextContents.Append("Aircraft serviceability till date for the month: " + mServiceabilityMailSend(0).AverageTillDay.ToString + " %")
            TextContents.Append(vbCrLf)
            TextContents.Append(vbCrLf)
        Else
            TextContents.Append("NO DATA FOUND FOR SELECTED DATE")
        End If
        Session("TextContents") = TextContents.ToString
        txtMail.Text = TextContents.ToString.Replace("<b>", "").Replace("</b>", "").Replace("<p>", "").Replace("</p>", "")
        txtMail.DataBind()
    End Sub
    Private Sub ControlVisibility()
        If mServiceabilityMailSend.Count <= 0 Then
            btnSendMail.Enabled = False
        Else
            btnSendMail.Enabled = True
        End If
    End Sub
#End Region

#Region "Events"
    Private Sub wfServiceabilityMailSend_Ajax_Load(ByVal sender As Object, ByVal e As System.EventArgs) Handles Me.Load
        getSession()
        If Not IsPostBack Then
            txtMailIDs.Focus()

            txtMailIDs.Text = Session("UserEmailID")
            txtMailIDs.DataBind()
            txtCCIDs.Text = Session("UserCcEmailID")
            txtCCIDs.DataBind()

            txtAsOnDate.Text = Session("ServDate")
            FindNow(Session("ServDate"))
            ControlVisibility()
        End If
    End Sub
    Private Sub btnSendMail_Click(ByVal sender As Object, ByVal e As System.EventArgs) Handles btnSendMail.Click
        Dim str As String = ""

        str = str + ("<html>" & "<head>" & "</head>" & "<body >")
        'str = str + ("<P><font face=""Calibri"">Dear " + "Sir" + ",</font></P> " & "<font face=""Calibri""><p> " + "<font face=""Calibri"">The following aircraft are available for flying on  <b>" & txtAsOnDate.Text & ":</b></font></p> ")
        str = str + ("<P><font face=""Calibri"">Dear " + "All" + ",</font></P> ")
        str = str + ("<font face=""Calibri"">")
        str = str + Session("TextContents").ToString.Replace(vbCrLf, "<br>")
        str = str + ("</font>")

        str = str + ("</body></html>")

        'str = str + ("<p>&nbsp;</p>")
        If txtRemark.Text.Trim = "" Then
            'Do nothing 
        Else
            str = str + ("<p><font face=""Calibri""> <b> Remark : " & txtRemark.Text.Trim & "</b></font></p>")
        End If

        str = str + ("<p><font face=""Calibri"">")
        str = str + ("<p><font face=""Calibri""><b>Report generated at : </b>" & Now.ToString("dd-MMM-yyyy") & "," & Now.ToString("hh:mm tt") & "</font></p>")
        If txtReportGenratedBy.Text.Trim = "" Then
            'Do nothing 
        Else
            str = str + ("<p><font face=""Calibri""> <b> Report generated by : " & txtReportGenratedBy.Text.Trim & "</b></font></p>")
        End If
        
        str = str + ("Kindly Login into <b>FlyPal®</b> for more details.</p><p>&nbsp;</p><p>&nbsp;</p>")
        str = str + ("</font>")

        str = str + ("<p><p><font face=""Calibri"">")
        str = str + ("<b>Regards,</b></p></p>")
        str = str + ("</font>")

        str = str + ("<p><font face=""Calibri"">")
        str = str + ("<b>FlyPal® Service</b></p>")
        str = str + ("</font>")

        Try
            SendMailFile.SendMailFile(Nothing, Thread.CurrentPrincipal.Identity.Name, "Aircraft Availability For " + txtAsOnDate.Text, "", , "", _
                                      txtMailIDs.Text.Trim, txtCCIDs.Text.Trim, , True, MailBody:=str, BCCMailID:=txtBCCIDs.Text.Trim, _
                                      Remark:=Session("SendMailRemark"), ReportGeneratedBy:=Session("ReportGenratedBy"))
            ScriptManager.RegisterStartupScript(Me, Me.GetType(), "openTransDetail", MessageBox.Show("Mail Sent Successfully", False), True)
        Catch ex As Exception
            MSGBoxCtrl.show("Error", "Error Sending Mail", ex.InnerException.ToString + ex.Message.ToString, MsgBoxStyle.OkOnly, "")
        End Try
    End Sub
    Private Sub btnBack_Click(ByVal sender As Object, ByVal e As System.EventArgs) Handles btnClose.Click
        Session.Remove("mServiceabilityMailSend")
        Dim mopenas As String = Request.QueryString("Type")
        If Not mopenas Is Nothing AndAlso mopenas = "pup" Then
            ScriptManager.RegisterStartupScript(Me, Me.GetType, "onclose", "CallParentCallback();", True)
            Exit Sub
        End If
    End Sub
    Private Sub txtAsOnDate_TextChanged(sender As Object, e As System.EventArgs) Handles txtAsOnDate.TextChanged
        FindNow(CDate(txtAsOnDate.Text))
        ControlVisibility()
    End Sub
#End Region

    
End Class