'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class wfTLPDetail_Ajax

    '''<summary>
    '''MainStyle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MainStyle As Global.System.Web.UI.HtmlControls.HtmlLink

    '''<summary>
    '''Form1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Form1 As Global.System.Web.UI.HtmlControls.HtmlForm

    '''<summary>
    '''ScriptManager1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ScriptManager1 As Global.System.Web.UI.ScriptManager

    '''<summary>
    '''upnlMSGBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents upnlMSGBox As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''MSGBoxCtrl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MSGBoxCtrl As Global.Flypal.MSGBox

    '''<summary>
    '''pnlMain control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlMain As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''upnlTitle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents upnlTitle As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''lblTitle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTitle As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''upnlErrorList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents upnlErrorList As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''Validationsummary2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Validationsummary2 As Global.System.Web.UI.WebControls.ValidationSummary

    '''<summary>
    '''cvCustom control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cvCustom As Global.System.Web.UI.WebControls.CustomValidator

    '''<summary>
    '''cvDepartureDateTime control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cvDepartureDateTime As Global.System.Web.UI.WebControls.CustomValidator

    '''<summary>
    '''cvArrivalDateTime control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cvArrivalDateTime As Global.System.Web.UI.WebControls.CustomValidator

    '''<summary>
    '''rfvDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rfvDate As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''cvAirBornTime control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cvAirBornTime As Global.System.Web.UI.WebControls.CustomValidator

    '''<summary>
    '''cvPlace1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cvPlace1 As Global.System.Web.UI.WebControls.CustomValidator

    '''<summary>
    '''cvPlace2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cvPlace2 As Global.System.Web.UI.WebControls.CustomValidator

    '''<summary>
    '''CvTime control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CvTime As Global.System.Web.UI.WebControls.CustomValidator

    '''<summary>
    '''upnlDetails control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents upnlDetails As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''lblDateTime control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDateTime As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''calDateTime control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents calDateTime As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblFlightNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblFlightNo As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtFlightNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtFlightNo As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblLogPageNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblLogPageNo As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtLogPageNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtLogPageNo As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblPalceStar1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPalceStar1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblDepPlace control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDepPlace As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Place1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Place1 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblDateTimeStar1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDateTimeStar1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblUTCDateTimeStar1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblUTCDateTimeStar1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblDepDateTime control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDepDateTime As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblUTCDateTime control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblUTCDateTime As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''calDeparture control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents calDeparture As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''calDeparture_CalendarExtender control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents calDeparture_CalendarExtender As Global.AjaxControlToolkit.CalendarExtender

    '''<summary>
    '''DateTime_watermarkextender control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DateTime_watermarkextender As Global.AjaxControlToolkit.TextBoxWatermarkExtender

    '''<summary>
    '''CalUTCDateTime control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CalUTCDateTime As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''CalUTCDateTime_CalendarExtender control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CalUTCDateTime_CalendarExtender As Global.AjaxControlToolkit.CalendarExtender

    '''<summary>
    '''CalUTCDateTime_watermarkextender control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CalUTCDateTime_watermarkextender As Global.AjaxControlToolkit.TextBoxWatermarkExtender

    '''<summary>
    '''txtDepartureTime control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDepartureTime As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtUTCDepartureTime control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtUTCDepartureTime As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtDepartureTimeMaskedEditExtender control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDepartureTimeMaskedEditExtender As Global.AjaxControlToolkit.MaskedEditExtender

    '''<summary>
    '''txtUTCDepartureTimeMaskedEditExtender control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtUTCDepartureTimeMaskedEditExtender As Global.AjaxControlToolkit.MaskedEditExtender

    '''<summary>
    '''lblTakeOffStar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTakeOffStar As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblUTCTakeOffStar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblUTCTakeOffStar As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblTakeOffLocalDateTime control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTakeOffLocalDateTime As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblUTCTakeOffDateTime control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblUTCTakeOffDateTime As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''chkTakeOff control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkTakeOff As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''chkUTCTakeOff control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkUTCTakeOff As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''calTakeOffLocalDateTime control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents calTakeOffLocalDateTime As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''calTakeOffLocalDateTime_CalendarExtender control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents calTakeOffLocalDateTime_CalendarExtender As Global.AjaxControlToolkit.CalendarExtender

    '''<summary>
    '''calTakeOffLocalDateTime_watermarkextender control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents calTakeOffLocalDateTime_watermarkextender As Global.AjaxControlToolkit.TextBoxWatermarkExtender

    '''<summary>
    '''calUTCTakeOffDateTime control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents calUTCTakeOffDateTime As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''calUTCTakeOffDateTime_CalendarExtender control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents calUTCTakeOffDateTime_CalendarExtender As Global.AjaxControlToolkit.CalendarExtender

    '''<summary>
    '''calUTCTakeOffDateTime_watermarkextender control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents calUTCTakeOffDateTime_watermarkextender As Global.AjaxControlToolkit.TextBoxWatermarkExtender

    '''<summary>
    '''txtTakeOffLocalTime control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTakeOffLocalTime As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtUTCTakeOffTime control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtUTCTakeOffTime As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtTakeOffLocalTimeMaskededitextender control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTakeOffLocalTimeMaskededitextender As Global.AjaxControlToolkit.MaskedEditExtender

    '''<summary>
    '''txtUTCTakeOffTimeMaskededitextender control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtUTCTakeOffTimeMaskededitextender As Global.AjaxControlToolkit.MaskedEditExtender

    '''<summary>
    '''lblPlaceStar2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPlaceStar2 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblArrPlace control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblArrPlace As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Place2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Place2 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btnAddPlaces control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnAddPlaces As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''lblUTCDateTimeStar2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblUTCDateTimeStar2 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblDateTimeStar2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDateTimeStar2 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblArrDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblArrDate As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblUTCArrivalDateTime control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblUTCArrivalDateTime As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''chkArrival control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkArrival As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''chkUTCArrival control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkUTCArrival As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''calArrival control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents calArrival As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''calArrival_CalendarExtender control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents calArrival_CalendarExtender As Global.AjaxControlToolkit.CalendarExtender

    '''<summary>
    '''calArrival_watermarkextender control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents calArrival_watermarkextender As Global.AjaxControlToolkit.TextBoxWatermarkExtender

    '''<summary>
    '''CalUTCArrival control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CalUTCArrival As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''CalUTCArrival_CalendarExtender control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CalUTCArrival_CalendarExtender As Global.AjaxControlToolkit.CalendarExtender

    '''<summary>
    '''CalUTCArrival_watermarkextender control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CalUTCArrival_watermarkextender As Global.AjaxControlToolkit.TextBoxWatermarkExtender

    '''<summary>
    '''txtArrivalTime control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtArrivalTime As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtUTCArrivalTime control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtUTCArrivalTime As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtArrivalTimeMaskedEditExtender control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtArrivalTimeMaskedEditExtender As Global.AjaxControlToolkit.MaskedEditExtender

    '''<summary>
    '''txtUTCArrivalTimeMaskedEditExtender control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtUTCArrivalTimeMaskedEditExtender As Global.AjaxControlToolkit.MaskedEditExtender

    '''<summary>
    '''lblTouchDownStar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTouchDownStar As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblUTCTouchDownStar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblUTCTouchDownStar As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblTouchDownLocalDateTime control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTouchDownLocalDateTime As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblUTCTouchDownDateTime control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblUTCTouchDownDateTime As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''chkTouchDown control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkTouchDown As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''chkUTCTouchDown control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkUTCTouchDown As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''calTouchDownLocalDateTime control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents calTouchDownLocalDateTime As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''calTouchDownLocalDateTime_CalendarExtender control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents calTouchDownLocalDateTime_CalendarExtender As Global.AjaxControlToolkit.CalendarExtender

    '''<summary>
    '''calTouchDownLocalDateTime_watermarkextender control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents calTouchDownLocalDateTime_watermarkextender As Global.AjaxControlToolkit.TextBoxWatermarkExtender

    '''<summary>
    '''calUTCTouchDownDateTime control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents calUTCTouchDownDateTime As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''calUTCTouchDownDateTime_CalendarExtender control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents calUTCTouchDownDateTime_CalendarExtender As Global.AjaxControlToolkit.CalendarExtender

    '''<summary>
    '''calUTCTouchDownDateTime_watermarkextender control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents calUTCTouchDownDateTime_watermarkextender As Global.AjaxControlToolkit.TextBoxWatermarkExtender

    '''<summary>
    '''txtTouchDownLocalTime control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTouchDownLocalTime As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtUTCTouchDownTime control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtUTCTouchDownTime As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtTouchDownLocalTimeMaskedEditExtender control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTouchDownLocalTimeMaskedEditExtender As Global.AjaxControlToolkit.MaskedEditExtender

    '''<summary>
    '''txtUTCTouchDownTimeMaskedEditExtender control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtUTCTouchDownTimeMaskedEditExtender As Global.AjaxControlToolkit.MaskedEditExtender

    '''<summary>
    '''lblairfly control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblairfly As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtBlockTime control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtBlockTime As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Label1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblAirBorneTime control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAirBorneTime As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtAirBorneTime control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAirBorneTime As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Label2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label2 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblLandings control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblLandings As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtLandings control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtLandings As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Label3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label3 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''tabLogDetailsContainer control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tabLogDetailsContainer As Global.AjaxControlToolkit.TabContainer

    '''<summary>
    '''tabLogFuel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tabLogFuel As Global.AjaxControlToolkit.TabPanel

    '''<summary>
    '''Label7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label7 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblFuelOnDeparture control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblFuelOnDeparture As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtFuelOnDeparture control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtFuelOnDeparture As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Label4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label4 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtFuelOnAdded control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtFuelOnAdded As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblFuelWt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblFuelWt As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblFuelUplifted control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblFuelUplifted As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtFuelUplifted control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtFuelUplifted As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblTotalFuelOnDeparture control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTotalFuelOnDeparture As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtTotalFuelOnDeparture control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTotalFuelOnDeparture As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblFuelOnArrival control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblFuelOnArrival As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtFuelOnArrival control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtFuelOnArrival As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblFuelConsumption control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblFuelConsumption As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtFuelConsumption control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtFuelConsumption As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''tabWeight control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tabWeight As Global.AjaxControlToolkit.TabPanel

    '''<summary>
    '''lblPaxAdult control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPaxAdult As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtPaxAdult control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPaxAdult As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblPaxChild control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPaxChild As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtPaxChild control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPaxChild As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblPaxInfant control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPaxInfant As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtPaxInfant control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPaxInfant As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblCargoWeight control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCargoWeight As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtCargoWeight control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCargoWeight As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblTakeOffWeight control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTakeOffWeight As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtTakeOffWeight control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTakeOffWeight As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblExtraBaggage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblExtraBaggage As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtExtraBaggage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtExtraBaggage As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TabEngineOil control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TabEngineOil As Global.AjaxControlToolkit.TabPanel

    '''<summary>
    '''Label5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label5 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtLHEngineOil control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtLHEngineOil As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Label6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label6 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtRHEngineOil control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtRHEngineOil As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TabPFI control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TabPFI As Global.AjaxControlToolkit.TabPanel

    '''<summary>
    '''upnlEmp control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents upnlEmp As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''Validationsummary1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Validationsummary1 As Global.System.Web.UI.WebControls.ValidationSummary

    '''<summary>
    '''cvSearch control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cvSearch As Global.System.Web.UI.WebControls.CustomValidator

    '''<summary>
    '''chkIsPFIDone control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkIsPFIDone As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''txtEmployee control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtEmployee As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtEmployee_Autocomplete control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtEmployee_Autocomplete As Global.AjaxControlToolkit.AutoCompleteExtender

    '''<summary>
    '''UpdatePanel1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanel1 As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''lblTLPGridTitle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTLPGridTitle As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''UpdatePanel2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanel2 As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''btnAdd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnAdd As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''upnlGrid control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents upnlGrid As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''dgLogTLPDetails control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dgLogTLPDetails As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''upnlButtons control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents upnlButtons As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''btnPrint control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnPrint As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnBack control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnBack As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''AjaxLoader control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AjaxLoader As Global.System.Web.UI.UpdateProgress

    '''<summary>
    '''btnDummyPlace control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnDummyPlace As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''pnlPlace control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlPlace As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''mdlPopupPlace control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents mdlPopupPlace As Global.AjaxControlToolkit.ModalPopupExtender
End Class
